scenario:
  mode: "eval"
  deterministic: True
  randomize_aisle_width: False

  eval_scenarios:
    - id: "1"
      d_path: "0.0"
      alignment_mode: "aligned"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "2"
      d_path: "0.1"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "3"
      d_path: "0.2"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "4"
      d_path: "0.3"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "5"
      d_path: "0.4"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "6"
      d_path: "0.5"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "7"
      d_path: "0.57"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "8"
      d_path: "0.59"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "9"
      d_path: "0.6"
      alignment_mode: "unaligned-top-bottom"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "10"
      d_path: "0.1"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "11"
      d_path: "0.2"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "12"
      d_path: "0.3"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "13"
      d_path: "0.4"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "14"
      d_path: "0.5"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "15"
      d_path: "0.57"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "16"
      d_path: "0.59"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"

    - id: "17"
      d_path: "0.6"
      alignment_mode: "unaligned-bottom-top"
      x_r: "-6"
      x_h: "5.9"
      x_goal_r: "5"
      x_goal_h: "-6"
