scenario:
  mode: "train"
  deterministic: False

  aisle_width: [6, 6] #ORIGINAL 5
#  aisle_center_y: 0.0

  offset_from_center: ["left", "right", "middle"]
  alignment_mode: "both" # set alignment mode options:"both", "aligned-middle","aligned-middle","aligned-right","unaligned-lr-middle","unaligned-lr-near-left","unaligned-lr-near-right","unaligned-rl-middle","unaligned-rl-near-left","unaligned-rl-near-right"

